version: '3'

services:
  # name of container
  ocpandacoin:
#    image: overcookedpanda/ocpandacoin:ubuntu-master-62cf102-Debug
    image: overcookedpanda/ocpandacoin:master-3f17124
    ports:
      - 0.0.0.0:8077:8077   # p2p
      - 0.0.0.0:8332:8332 # rpc
      - 127.0.0.1:28032:28032 # zmq raw blocks
    volumes:
#      - ./ocpandacoin:/home/btcsq/.btcsq:rw
      - ./ocpandacoin:/home/ocpandacoin/.ocpandacoin:rw
    command: sh -c 'sleep 7 && ocpandacoind'
